### ISSUE TITLE
Use the scripts for linux/arm64

### ISSUE THREAD

**Issue by dbogatov** [krumeich/biber-alpine#2]
Hi!

Do you think your scripts can be used to build biber for `linux/arm64` debian?
With slight modification, that is.

**Comment by krumeich** [comment]
Hi, that would be possible, I guess. When designing the process, the main problem was to find a suitable base image that contained the right version of Perl. As far as I understand it, Biber usually requires a relatively recent Perl. Since Debian isn't famous for shipping the latest versions, you might have to compile Perl yourself.

**Comment by krumeich** [comment]
Thought about your question again. I think that the Docker based toolchain is pretty flexible when it comes to the target os and platform. One could probably adapt the Dockerfile so that it covers not only several architectures, but also several operating systems.

My guess is, however, that you'd need to to add your own directory in the `dist` tree in biber itself. When I started contributing the MUSL version for x86_64, I had to add my own distribution method, which @plk had to merge into the biber code base. Check out the commits leading up to https://github.com/plk/biber/commit/68f42231bc31d80192d512c7bf5910606bf5f548.

**Comment by dbogatov** [comment]
@krumeich Thanks! I ended up using your code and adjusting it for Debian ARM64. Unfortunately, I was not able to produce a standalone biber binary with perl and dependencies, but I was able to run the biber code in Docker. So at the end of the day, my image is larger than it could have been, but otherwise working. See here

https://git.dbogatov.org/dbogatov/docker-images/-/blob/master/images/latex/build-biber-pdfjam.sh

This script assumes that the latex distribution for Debian ARM is installed (without biber).

**Comment by krumeich** [comment]
Congratulations! This looks good. 

One more thing: If you want to test biber a bit more deeply than just checking whether it runs, there are two test files that you could use (see my `bibertest.sh`script):

```
/usr/local/bin/biber --validate-control test-dev.bcf
/usr/local/bin/biber --convert-control test-dev.bcf
```

This has been sufficient as integration tests for me.
